---
title: "Análise de Dados Socioeconômicos Brasil XXI"
author: "Luiz Antônio Gouveia de Oliveira"
date: "07/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 1. Instalando e carregando os pacotes analíticos
```{r}
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.


library(tidyverse)
library(Hmisc)
library(viridis)
library(plotly)
library(gapminder)
library(RColorBrewer)
library(ggthemes)
library(cowplot)
library(gghighlight)
library(IndexNumber)
library(IndexNumR)
library(purrr)
library(tidytable)
library(here)

```

### 2. Carregamento das Bases de Dados
```{r}

here("/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century")

Human_develop_index <- read_delim("/Users/MAC/Documents/Ambiente R/Brasil Inicio Séc XXI/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw Data/CSV Files/HDI.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

write.table(Human_develop_index, file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw/CSV Files/Human_development_index.csv", sep=',', quote=F, row.names=F)


Environm_social_governm <-  read_csv("/Users/MAC/Documents/Ambiente R/Brasil Inicio Séc XXI/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw Data/CSV Files/Data_Extract_From_Environment_Social_and_Governance_(ESG)_Data 2001 2018 csv/c8024182-34d3-4f8a-9684-c63ab2d952c2_Data.csv", 
    na = "NA")

write.table(Environm_social_governm, file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw/CSV Files/Environm_social_governm.csv", sep=',', quote=F, row.names=F)


Poverty_equity <- read_csv("/Users/MAC/Documents/Ambiente R/Brasil Inicio Séc XXI/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw Data/CSV Files/Data_Extract_From_Poverty_and_Equity 2001 2018 csv/303edb4a-4c02-4724-b692-8fc52968c5c2_Data.csv")

write.table(Poverty_equity, file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw/CSV Files/Poverty_equity.csv", sep=',', quote=F, row.names=F)


Sustain_developm_goal <- read_csv("/Users/MAC/Documents/Ambiente R/Brasil Inicio Séc XXI/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw Data/CSV Files/Data_Extract_From_Sustainable_Development_Goals_(SDGs) 2001 2018 csv/a4fe0872-8289-49fd-9171-dc6d42f8109c_Data.csv")


write.table(Sustain_developm_goal, file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw/CSV Files/Sustain_developm_goal.csv", sep=',', quote=F, row.names=F)


# economic_indicators <- read_csv("/Users/MAC/Documents/Ambiente R/Brasil Inicio Séc XXI/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw Data/CSV Files/Data_Extract_From_Worldwide_Governance_Indicators 2001 2018 csv/1207e476-959b-4af8-b65e-2f0ed92807f1_Data.csv")

# write.table(economic_indicators, file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Raw/CSV Files/economic_indicators.csv", sep=',', quote=F, row.names=F)



```


### 3. Tratamento das bases de dados
```{r}
# selecionando as variáveis de análise

gdp_per_capita_ppp <- Sustain_developm_goal %>%
  filter(`Series Code`=="NY.GDP.PCAP.PP.CD") %>%
  select(`Country Name`, `2001 [YR2001]`:`2018 [YR2018]`)
gdp_per_capita_ppp$`Country Name` <- gsub("Brazil", "Brasil", gdp_per_capita_ppp$`Country Name`)
gdp_per_capita_ppp$`Country Name` <- gsub("World", "Mundo", gdp_per_capita_ppp$`Country Name`)

access_eletricity <- Environm_social_governm %>%
  filter(`Series Code` == "EG.ELC.ACCS.ZS") %>%
  select(`Country Name`, `2001 [YR2001]`:`2017 [YR2017]`)
access_eletricity$`Country Name` <- gsub("Brazil", "Brasil", access_eletricity$`Country Name`)
access_eletricity$`Country Name` <- gsub("World", "Mundo", access_eletricity$`Country Name`)

government_effectiveness <- Environm_social_governm %>%
  filter(`Series Code` == "GE.EST") %>%
  select(`Country Name`, `2002 [YR2002]`:`2017 [YR2017]`)
government_effectiveness$`Country Name` <- gsub("Brazil", "Brasil", government_effectiveness$`Country Name`)
government_effectiveness$`Country Name` <- gsub("World", "Mundo", government_effectiveness$`Country Name`)

internet <- Environm_social_governm %>%
  filter(`Series Code` == "IT.NET.USER.ZS") %>%
  select(`Country Name`, `2001 [YR2001]`:`2018 [YR2018]`)
internet$`Country Name` <- gsub("Brazil", "Brasil", internet$`Country Name`)
internet$`Country Name` <- gsub("World", "Mundo", internet$`Country Name`)

# Removendo o dataset do ambiente global do R
rm(Environm_social_governm)

basic_sanitation <- Sustain_developm_goal %>%
  filter(`Series Code` == "SH.STA.BASS.ZS")  %>%
  select(`Country Name`, `2001 [YR2001]`:`2017 [YR2017]`)
basic_sanitation$`Country Name` <- gsub("Brazil", "Brasil", basic_sanitation$`Country Name`)
basic_sanitation$`Country Name` <- gsub("World", "Mundo", basic_sanitation$`Country Name`)

# Removendo o dataset do ambiente global do R
rm(Sustain_developm_goal)



gini <- Poverty_equity %>%
  filter(`Series Code`=="SI.POV.GINI") %>%
  select(`Country Name`, `2001 [YR2001]`:`2017 [YR2017]`)
gini$`Country Name` <- gsub("Brazil", "Brasil", gini$`Country Name`)
gini$`Country Name` <- gsub("World", "Mundo", gini$`Country Name`)

total_population <- Poverty_equity %>%
  filter(`Series Code` == "SP.POP.TOTL") %>%
  select(`Country Name`, `2001 [YR2001]`:`2017 [YR2017]`)
total_population$`Country Name` <- gsub("Brazil", "Brasil", total_population$`Country Name`)
total_population$`Country Name` <- gsub("World", "Mundo", total_population$`Country Name`)


# Removendo o dataset do ambiente global do R
rm(Poverty_equity)


hdi <- select(Human_develop_index, "Country", "2001":"2018")
hdi$Country <- gsub("Brazil", "Brasil", hdi$Country)
hdi$Country <- gsub("World", "Mundo", hdi$Country)

# Removendo o dataset do ambiente global do R
rm(Human_develop_index)



# Checando os datasets

#str(gdp_per_capita_ppp)
#str(gini)
#str(hdi)
#str(access_eletricity)
#str(government_effectiveness)
#str(internet)
#str(basic_sanitation)
#str(total_population)


# Transformando HDI de 'character' para 'double'
hdi[ , c(2:19)] <- lapply(hdi[c(2:19)], as.double)


# Renomeando as colunas de anos
colnames(gini)[2:18] <- '2001':'2017'
colnames(gdp_per_capita_ppp)[2:19] <- '2001':'2018'
colnames(access_eletricity)[2:18] <- '2001':'2017'
colnames(government_effectiveness)[2:17] <- '2002':'2017'
colnames(internet)[2:19] <- '2001':'2018'
colnames(basic_sanitation)[2:18] <- '2001':'2017'
colnames(total_population)[2:18] <- '2001':'2017'


# Exportando as bases de dados brutas para a pasta de dados processados

write.table(hdi, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/hdi.csv", sep=',', quote=F, row.names=F)

write.table(gdp_per_capita_ppp, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/gdp_per_capita_ppp.csv", sep=',', quote=F, row.names=F)

write.table(access_eletricity, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/access_eletricity.csv", sep=',', quote=F, row.names=F)

write.table(government_effectiveness, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/government_effectiveness.csv", sep=',', quote=F, row.names=F)

write.table(internet, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/internet.csv", sep=',', quote=F, row.names=F)

write.table(basic_sanitation, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/basic_sanitation.csv", sep=',', quote=F, row.names=F)

write.table(total_population, file="//Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Data/Processed/total_population.csv", sep=',', quote=F, row.names=F)


```

### 4. Calculando os números-índice
```{r}

hdi_indice <- hdi %>%
  mutate(hdi$`2001`/hdi$`2001`*100, hdi$`2002`/hdi$`2001`*100, hdi$`2003`/hdi$`2002`*100, hdi$`2004`/hdi$`2003`*100, hdi$`2005`/hdi$`2004`*100, hdi$`2006`/hdi$`2005`*100, hdi$`2007`/hdi$`2006`*100, hdi$`2008`/hdi$`2007`*100, hdi$`2009`/hdi$`2008`*100, hdi$`2010`/hdi$`2009`*100, hdi$`2011`/hdi$`2010`*100, hdi$`2012`/hdi$`2011`*100, hdi$`2013`/hdi$`2012`*100, hdi$`2014`/hdi$`2013`*100, hdi$`2015`/hdi$`2014`*100, hdi$`2016`/hdi$`2015`*100, hdi$`2017`/hdi$`2016`*100, hdi$`2018`/hdi$`2017`*100) %>% 
  filter(Country %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo")) %>%
  select(1, 20:37)

names(hdi_indice)[2:19] = c("2001":"2018")


gdp_indice <- gdp_per_capita_ppp %>%
  mutate(gdp_per_capita_ppp$`2001`/gdp_per_capita_ppp$`2001`*100, gdp_per_capita_ppp$`2002`/gdp_per_capita_ppp$`2001`*100, gdp_per_capita_ppp$`2003`/gdp_per_capita_ppp$`2002`*100, gdp_per_capita_ppp$`2004`/gdp_per_capita_ppp$`2003`*100, gdp_per_capita_ppp$`2005`/gdp_per_capita_ppp$`2004`*100, gdp_per_capita_ppp$`2006`/gdp_per_capita_ppp$`2005`*100, gdp_per_capita_ppp$`2007`/gdp_per_capita_ppp$`2006`*100, gdp_per_capita_ppp$`2008`/gdp_per_capita_ppp$`2007`*100, gdp_per_capita_ppp$`2009`/gdp_per_capita_ppp$`2008`*100, gdp_per_capita_ppp$`2010`/gdp_per_capita_ppp$`2009`*100, gdp_per_capita_ppp$`2011`/gdp_per_capita_ppp$`2010`*100, gdp_per_capita_ppp$`2012`/gdp_per_capita_ppp$`2011`*100, gdp_per_capita_ppp$`2013`/gdp_per_capita_ppp$`2012`*100, gdp_per_capita_ppp$`2014`/gdp_per_capita_ppp$`2013`*100, gdp_per_capita_ppp$`2015`/gdp_per_capita_ppp$`2014`*100, gdp_per_capita_ppp$`2016`/gdp_per_capita_ppp$`2015`*100, gdp_per_capita_ppp$`2017`/gdp_per_capita_ppp$`2016`*100, gdp_per_capita_ppp$`2018`/gdp_per_capita_ppp$`2017`*100) %>% 
  select(1, 20:37)

names(gdp_indice)[2:19] = c("2001":"2018")


internet_indice <- internet %>%
  mutate(internet$`2001`/internet$`2001`*100, internet$`2002`/internet$`2001`*100, internet$`2003`/internet$`2002`*100, internet$`2004`/internet$`2003`*100, internet$`2005`/internet$`2004`*100, internet$`2006`/internet$`2005`*100, internet$`2007`/internet$`2006`*100, internet$`2008`/internet$`2007`*100, internet$`2009`/internet$`2008`*100, internet$`2010`/internet$`2009`*100, internet$`2011`/internet$`2010`*100, internet$`2012`/internet$`2011`*100, internet$`2013`/internet$`2012`*100, internet$`2014`/internet$`2013`*100, internet$`2015`/internet$`2014`*100, internet$`2016`/internet$`2015`*100, internet$`2017`/internet$`2016`*100, internet$`2018`/internet$`2017`*100) %>% 
  select(1, 20:37)

names(internet_indice)[2:19] = c("2001":"2018")


gini_indice <- gini %>%
  mutate(gini$`2001`/gini$`2001`*100, gini$`2002`/gini$`2001`*100, gini$`2003`/gini$`2002`*100, gini$`2004`/gini$`2003`*100, gini$`2005`/gini$`2004`*100, gini$`2006`/gini$`2005`*100, gini$`2007`/gini$`2006`*100, gini$`2008`/gini$`2007`*100, gini$`2009`/gini$`2008`*100, gini$`2010`/gini$`2009`*100, gini$`2011`/gini$`2010`*100, gini$`2012`/gini$`2011`*100, gini$`2013`/gini$`2012`*100, gini$`2014`/gini$`2013`*100, gini$`2015`/gini$`2014`*100, gini$`2016`/gini$`2015`*100, gini$`2017`/gini$`2016`*100) %>% 
  select(1, 19:35)

names(gini_indice)[2:18] = c("2001":"2017")

eletricity_indice <- access_eletricity %>%
  mutate(access_eletricity$`2001`/access_eletricity$`2001`*100, access_eletricity$`2002`/access_eletricity$`2001`*100, access_eletricity$`2003`/access_eletricity$`2002`*100, access_eletricity$`2004`/access_eletricity$`2003`*100, access_eletricity$`2005`/access_eletricity$`2004`*100, access_eletricity$`2006`/access_eletricity$`2005`*100, access_eletricity$`2007`/access_eletricity$`2006`*100, access_eletricity$`2008`/access_eletricity$`2007`*100, access_eletricity$`2009`/access_eletricity$`2008`*100, access_eletricity$`2010`/access_eletricity$`2009`*100, access_eletricity$`2011`/access_eletricity$`2010`*100, access_eletricity$`2012`/access_eletricity$`2011`*100, access_eletricity$`2013`/access_eletricity$`2012`*100, access_eletricity$`2014`/access_eletricity$`2013`*100, access_eletricity$`2015`/access_eletricity$`2014`*100, access_eletricity$`2016`/access_eletricity$`2015`*100, access_eletricity$`2017`/access_eletricity$`2016`*100) %>% 
  select(1, 19:35)

names(eletricity_indice)[2:18] = c("2001":"2017")


#government_indice <- government_effectiveness %>% 
  #mutate(government_effectiveness$`2002`/government_effectiveness$`2002`*100, government_effectiveness$`2003`/government_effectiveness$`2002`*100, government_effectiveness$`2004`/government_effectiveness$`2003`*100, government_effectiveness$`2005`/government_effectiveness$`2004`*100, government_effectiveness$`2006`/government_effectiveness$`2005`*100, government_effectiveness$`2007`/government_effectiveness$`2006`*100, government_effectiveness$`2008`/government_effectiveness$`2007`*100, government_effectiveness$`2009`/government_effectiveness$`2008`*100, government_effectiveness$`2010`/government_effectiveness$`2009`*100, government_effectiveness$`2011`/government_effectiveness$`2010`*100, government_effectiveness$`2012`/government_effectiveness$`2011`*100, government_effectiveness$`2013`/government_effectiveness$`2012`*100, government_effectiveness$`2014`/government_effectiveness$`2013`*100, government_effectiveness$`2015`/government_effectiveness$`2014`*100, government_effectiveness$`2016`/government_effectiveness$`2015`*100, government_effectiveness$`2017`/government_effectiveness$`2016`*100) %>% 
  #select(1, 19:35)

#names(government_indice)[2:13] = c("2002":"2017")



sanitation_indice <-basic_sanitation %>%
  mutate(basic_sanitation$`2001`/basic_sanitation$`2001`*100, basic_sanitation$`2002`/basic_sanitation$`2001`*100, basic_sanitation$`2003`/basic_sanitation$`2002`*100, basic_sanitation$`2004`/basic_sanitation$`2003`*100, basic_sanitation$`2005`/basic_sanitation$`2004`*100, basic_sanitation$`2006`/basic_sanitation$`2005`*100, basic_sanitation$`2007`/basic_sanitation$`2006`*100, basic_sanitation$`2008`/basic_sanitation$`2007`*100, basic_sanitation$`2009`/basic_sanitation$`2008`*100, basic_sanitation$`2010`/basic_sanitation$`2009`*100, basic_sanitation$`2011`/basic_sanitation$`2010`*100, basic_sanitation$`2012`/basic_sanitation$`2011`*100, basic_sanitation$`2013`/basic_sanitation$`2012`*100, basic_sanitation$`2014`/basic_sanitation$`2013`*100, basic_sanitation$`2015`/basic_sanitation$`2014`*100, basic_sanitation$`2016`/basic_sanitation$`2015`*100, basic_sanitation$`2017`/basic_sanitation$`2016`*100) %>% 
  select(1, 19:35)

names(sanitation_indice)[2:18] = c("2001":"2017")



pop_indice <-total_population %>%
  mutate(total_population$`2001`/total_population$`2001`*100, total_population$`2002`/total_population$`2001`*100, total_population$`2003`/total_population$`2002`*100, total_population$`2004`/total_population$`2003`*100, total_population$`2005`/total_population$`2004`*100, total_population$`2006`/total_population$`2005`*100, total_population$`2007`/total_population$`2006`*100, total_population$`2008`/total_population$`2007`*100, total_population$`2009`/total_population$`2008`*100, total_population$`2010`/total_population$`2009`*100, total_population$`2011`/total_population$`2010`*100, total_population$`2012`/total_population$`2011`*100, total_population$`2013`/total_population$`2012`*100, total_population$`2014`/total_population$`2013`*100, total_population$`2015`/total_population$`2014`*100, total_population$`2016`/total_population$`2015`*100, total_population$`2017`/total_population$`2016`*100) %>% 
  select(1, 19:35)

names(pop_indice)[2:18] = c("2001":"2017")


 

```



### 5. Inspeção das Bases de Dados
```{r}
# Inspecionando os datasets
# names(gdp_per_capita_ppp)
# head(gdp_per_capita_ppp)
# tail(gdp_per_capita_ppp)
# summary(gdp_per_capita_ppp)

# names(gini)
# head(gini)
# tail(gini)
# summary(gini)

# describe(hdi)


# Reorganizando os datasets
hdi_2 <- hdi %>% 
  gather(Year, Index, `2001`:`2018`) %>%
  arrange(Country) %>%
  na.omit()


 hdi_indice_index <- hdi_indice %>% 
  gather(Year, Index, `2001`:`2018`) %>%
  arrange(Country) %>%
  na.omit()

gdp_per_capita_ppp_2 <- gdp_per_capita_ppp %>% 
  gather(Year, Index, `2001`:`2018`) %>%
  arrange(`Country Name`) %>%
  na.omit()

gdp_indice_index <- gdp_indice %>% 
  gather(Year, Index, `2001`:`2018`) %>%
  arrange(`Country Name`) %>%
  na.omit()

gini_2 <- gini %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()


gini_indice_index <- gini_indice %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

access_eletricity_2 <- access_eletricity %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

eletricity_indice_index <- eletricity_indice %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

government_effectiveness_2 <- government_effectiveness %>% 
  gather(Year, Index, `2002`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

internet_2 <- internet %>% 
  gather(Year, Index, `2001`:`2018`) %>%
  arrange(`Country Name`) %>%
  na.omit()

internet_indice_index <- internet_indice %>% 
  gather(Year, Index, `2001`:`2018`) %>%
  arrange(`Country Name`) %>%
  na.omit()

basic_sanitation_2 <- basic_sanitation %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

sanitation_indice_index <- sanitation_indice %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

total_population_2 <- total_population %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()

pop_indice_index <- pop_indice %>% 
  gather(Year, Index, `2001`:`2017`) %>%
  arrange(`Country Name`) %>%
  na.omit()


# Calculando os números-índice






# Selecionando os países de interesse

EVOL_HDI <- hdi %>% 
  filter(Country %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

EVOL_HDI_INDICE <- hdi_indice %>% 
  filter(Country %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa", "Mundo"))

EVOL_GINI <- gini %>% 
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

EVOL_GINI_INDICE <- gini_indice %>% 
   filter(`Country Name` %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa"))

EVOL_GDP_PC <- gdp_per_capita_ppp %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

EVOL_GDP_PC_INDICE <- gdp_indice %>%
   filter(`Country Name` %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa", "Mundo"))

EVOL_ACC_ELE <- access_eletricity %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

EVOL_ACC_ELE_INDICE <- eletricity_indice %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa", "Mundo"))

GOV_EFE <- government_effectiveness %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

INTER_ACC <- internet %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

INTER_ACC_INDICE <- internet_indice %>%
   filter(`Country Name` %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa", "Mundo"))

BAS_SAN <- basic_sanitation %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

BAS_SAN_INDICE <- sanitation_indice %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa", "Mundo"))

TOTAL_POP <- total_population %>%
  filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey", "Mundo"))

TOTAL_POP_INDICE <- pop_indice %>%
    filter(`Country Name` %in% c("Brasil", "Colombia", "Mexico", "Russia", "South Africa", "Turkey", "Mundo"))




 
# Agrupando os indicadores dos países similares

sim_countries_hdi <- hdi %>% 
  filter(Country %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
  select(`Country`, `2001`:`2018`)
sim_countries_hdi[, 2:19] <- sapply(sim_countries_hdi[, 2:19], as.numeric)


sim_countries_pop <- total_population %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

sim_countries_san <- basic_sanitation %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

sim_countries_inter <- internet %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

sim_countries_ele <- access_eletricity %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

sim_countries_gini <- gini %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

sim_countries_gov <- government_effectiveness %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))

sim_countries_gdp <- gdp_per_capita_ppp %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey"))


# Agrupando os numeros-indice dos países similares

ind_sim_countries_hdi <- hdi_indice %>% 
  filter(Country %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
  select(`Country`, `2001`:`2018`)
ind_sim_countries_hdi[, 2:19] <- sapply(ind_sim_countries_hdi[, 2:19], as.numeric)


ind_sim_countries_pop <- sanitation_indice %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
  select(`Country Name`, `2001`:`2017`)
ind_sim_countries_pop[, 2:18] <- sapply(ind_sim_countries_pop[, 2:18], as.numeric)

ind_sim_countries_san <- sanitation_indice %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
 select(`Country Name`, `2001`:`2017`)
ind_sim_countries_san[, 2:18] <- sapply(ind_sim_countries_san[, 2:18], as.numeric)
 

ind_sim_countries_inter <- internet_indice %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
 select(`Country Name`, `2001`:`2017`)
ind_sim_countries_inter[, 2:18] <- sapply(ind_sim_countries_inter[, 2:18], as.numeric)
  

ind_sim_countries_ele <- eletricity_indice %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
 select(`Country Name`, `2001`:`2017`)
ind_sim_countries_ele[, 2:18] <- sapply(ind_sim_countries_ele[, 2:18], as.numeric)
  

ind_sim_countries_gini <- gini_indice %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
  select(`Country Name`, `2001`:`2017`)
ind_sim_countries_gini[, 2:18] <- sapply(ind_sim_countries_gini[, 2:18], as.numeric)
  

#ind_sim_countries_gov <- government_effectiveness %>% 
  #filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
 #select(`Country Name`, `2001`:`2017`)
#ind_sim_countries_gov[, 2:18] <- sapply(ind_sim_countries_gov[, 2:18], as.numeric)
   

ind_sim_countries_gdp <- gdp_indice %>% 
  filter(`Country Name` %in% c("Colombia", "Indonesia", "Malaysia", "Mexico", "Philippines", "Russia", "South Africa", "Thailand", "Turkey")) %>%
  select(`Country Name`, `2001`:`2017`)
ind_sim_countries_gdp[, 2:18] <- sapply(ind_sim_countries_gdp[, 2:18], as.numeric)
  


# Calculando medias dos indicadores dos países similares

sim_countries_gdp_mean <- plyr::colwise(mean)(sim_countries_gdp)
sim_countries_gdp_mean[1,1] <- "Média países similares"

sim_countries_ele_mean <- plyr::colwise(mean)(sim_countries_ele)
sim_countries_ele_mean[1,1] <- "Média países similares"

sim_countries_gini_mean <- plyr::colwise(mean)(sim_countries_gini)
sim_countries_gini_mean[1,1] <- "Média países similares"

sim_countries_gov_mean <- plyr::colwise(mean)(sim_countries_gov)
sim_countries_gov_mean[1,1] <- "Média países similares"

sim_countries_inter_mean <- plyr::colwise(mean)(sim_countries_inter)
sim_countries_inter_mean[1,1] <- "Média países similares"

sim_countries_hdi_mean <- plyr::colwise(mean)(sim_countries_hdi)
sim_countries_hdi_mean[1,1] <- "Média países similares"

sim_countries_san_mean <- plyr::colwise(mean)(sim_countries_san)
sim_countries_san_mean[1,1] <- "Média países similares"

sim_countries_pop_mean <- plyr::colwise(mean)(sim_countries_pop)
sim_countries_pop_mean[1,1] <- "Média países similares"


# Calculando medias dos indicadores em números-indice dos países similares

sim_countries_gdp_mean_ind <- plyr::colwise(mean)(ind_sim_countries_gdp)
sim_countries_gdp_mean_ind[1,1] <- "Média países similares"

sim_countries_ele_mean_ind <- plyr::colwise(mean)(ind_sim_countries_ele)
sim_countries_ele_mean_ind[1,1] <- "Média países similares"

sim_countries_gini_mean_ind <- plyr::colwise(mean)(ind_sim_countries_gini)
sim_countries_gini_mean_ind[1,1] <- "Média países similares"

#sim_countries_gov_mean_ind <- plyr::colwise(mean)(ind_sim_countries_gdp)
#sim_countries_gov_mean_ind[1,1] <- "Média países similares"

sim_countries_inter_mean_ind <- plyr::colwise(mean)(ind_sim_countries_inter)
sim_countries_inter_mean_ind[1,1] <- "Média países similares"

sim_countries_hdi_mean_ind <- plyr::colwise(mean)(ind_sim_countries_hdi)
sim_countries_hdi_mean_ind[1,1] <- "Média países similares"

sim_countries_san_mean_ind <- plyr::colwise(mean)(ind_sim_countries_san)
sim_countries_san_mean_ind[1,1] <- "Média países similares"

sim_countries_pop_mean_ind <- plyr::colwise(mean)(ind_sim_countries_pop)
sim_countries_pop_mean_ind[1,1] <- "Média países similares"




# Agrupando os indicadores do Brasil e do Mundo
EVOL_GDP_BZ_WD <- gdp_per_capita_ppp %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

EVOL_ACC_ELE_BZ_WD <- access_eletricity %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

EVOL_POP_BZ_WD <- total_population %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

EVOL_INTER_BZ_WD <- internet %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

EVOL_SAN_BZ_WD <- basic_sanitation %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

EVOL_GOV_BZ_WD <- government_effectiveness %>%
  filter(`Country Name` %in% "Brasil")

EVOL_HDI_BZ_WD <- hdi %>%
  filter(`Country` %in% c("Brasil", "Mundo"))

EVOL_GINI_BZ_WD <- gini %>%
  filter(`Country Name` %in% "Brasil")


# Agrupando os numeros-indice do Brasil e do Mundo
IND_EVOL_GDP_BZ_WD <- gdp_indice %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

IND_EVOL_ACC_ELE_BZ_WD <- eletricity_indice %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

IND_EVOL_POP_BZ_WD <- pop_indice %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

IND_EVOL_INTER_BZ_WD <- internet_indice %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

IND_EVOL_SAN_BZ_WD <- sanitation_indice %>%
  filter(`Country Name` %in% c("Brasil", "Mundo"))

#EVOL_GOV_BZ_WD <- government_effectiveness %>%
 # filter(`Country Name` %in% "Brasil")

IND_EVOL_HDI_BZ_WD <- hdi_indice %>%
  filter(`Country` %in% c("Brasil", "Mundo"))

IND_EVOL_GINI_BZ_WD <- gini_indice %>%
  filter(`Country Name` %in% "Brasil")




# Agrupando os índicadores do Brasil, do Mundo e da média dos países similares

media_bz_wd_sim_gdp <- bind_rows(EVOL_GDP_BZ_WD, sim_countries_gdp_mean)

media_bz_wd_sim_ele <- bind_rows(EVOL_ACC_ELE_BZ_WD, sim_countries_ele_mean)

media_bz_wd_sim_pop <- bind_rows(EVOL_POP_BZ_WD, sim_countries_pop_mean)

media_bz_wd_sim_inter <- bind_rows(EVOL_INTER_BZ_WD, sim_countries_inter_mean)

media_bz_wd_sim_san <- bind_rows(EVOL_SAN_BZ_WD, sim_countries_san_mean)

media_bz_wd_sim_gov <- bind_rows(EVOL_GOV_BZ_WD, sim_countries_gov_mean)

media_bz_wd_sim_hdi <- bind_rows(EVOL_HDI_BZ_WD, sim_countries_hdi_mean)

media_bz_wd_sim_gini <- bind_rows(EVOL_GINI_BZ_WD, sim_countries_gini_mean)


# Agrupando os números-indice do Brasil, do Mundo e da média dos países similares

ind_media_bz_wd_sim_gdp <- bind_rows(IND_EVOL_GDP_BZ_WD, sim_countries_gdp_mean_ind)

ind_media_bz_wd_sim_ele <- bind_rows(IND_EVOL_ACC_ELE_BZ_WD, sim_countries_ele_mean_ind)

ind_media_bz_wd_sim_pop <- bind_rows(IND_EVOL_POP_BZ_WD, sim_countries_pop_mean_ind)

ind_media_bz_wd_sim_inter <- bind_rows(IND_EVOL_INTER_BZ_WD, sim_countries_inter_mean_ind)

ind_media_bz_wd_sim_san <- bind_rows(IND_EVOL_SAN_BZ_WD, sim_countries_san_mean_ind)

#ind_media_bz_wd_sim_gov <- bind_rows(IND_EVOL_GOV_BZ_WD, sim_countries_gov_mean)

ind_media_bz_wd_sim_hdi <- bind_rows(IND_EVOL_HDI_BZ_WD, sim_countries_hdi_mean_ind)

ind_media_bz_wd_sim_gini <- bind_rows(IND_EVOL_GINI_BZ_WD, sim_countries_gini_mean_ind)



# Reorganizando os datasets 2
media_bz_wd_sim_gdp_2 <- media_bz_wd_sim_gdp %>%
  gather(Ano, Index, `2001`:`2018`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

media_bz_wd_sim_ele_2 <- media_bz_wd_sim_ele %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

media_bz_wd_sim_pop_2 <- media_bz_wd_sim_pop %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

media_bz_wd_sim_inter_2 <- media_bz_wd_sim_inter %>%
  gather(Ano, Index, `2001`:`2018`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()


media_bz_wd_sim_san_2 <- media_bz_wd_sim_san %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

#media_bz_wd_sim_gov_2 <- media_bz_wd_sim_gov %>%
 # gather(Ano, Index, `2002`:`2017`) %>% 
  #arrange(`Country Name`) %>% 
  #na.omit()

media_bz_wd_sim_hdi_2 <- media_bz_wd_sim_hdi %>%
  gather(Ano, Index, `2001`:`2018`) %>% 
  arrange(`Country`) %>% 
  na.omit()

media_bz_wd_sim_gini_2 <- media_bz_wd_sim_gini %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

#EVOL_GINI_2 <- EVOL_GINI %>%
 # filter(`Country Name` %in% c("Brasil", "Colombia", "Indonesia", "Thailand", "Turkey")) %>%
  #gather(Ano, Index, `2001`:`2017`) %>% 
  #arrange(`Country Name`) %>% 
  #na.omit()




# Reorganizando os datasets dos números-indice

ind_media_bz_wd_sim_gdp_index <- ind_media_bz_wd_sim_gdp %>%
  gather(Ano, Index, `2001`:`2018`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

ind_media_bz_wd_sim_ele_2 <- ind_media_bz_wd_sim_ele %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

ind_media_bz_wd_sim_pop_2 <- ind_media_bz_wd_sim_pop %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

ind_media_bz_wd_sim_inter_2 <- ind_media_bz_wd_sim_inter %>%
  gather(Ano, Index, `2001`:`2018`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()


ind_media_bz_wd_sim_san_2 <- ind_media_bz_wd_sim_san %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()

#ind_media_bz_wd_sim_gov_2 <- media_bz_wd_sim_gov %>%
 # gather(Ano, Index, `2002`:`2017`) %>% 
  #arrange(`Country Name`) %>% 
  #na.omit()

ind_media_bz_wd_sim_hdi_2 <- ind_media_bz_wd_sim_hdi %>%
  gather(Ano, Index, `2001`:`2018`) %>% 
  arrange(`Country`) %>% 
  na.omit()

ind_media_bz_wd_sim_gini_2 <- ind_media_bz_wd_sim_gini %>%
  gather(Ano, Index, `2001`:`2017`) %>% 
  arrange(`Country Name`) %>% 
  na.omit()



```





### 6. Gráficos

```{r message=TRUE, warning=TRUE, paged.print=TRUE}

# Plots

evol_pib_percapita <- media_bz_wd_sim_gdp_2 %>% 
   ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do PIB per capita", subtitle = "PIB per capita (PPP) em Dólares Internacionais (2001 - 2018)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

 ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_pib_percapita.png")
 
 
evol_acc_eletricitry <- media_bz_wd_sim_ele_2 %>%
   ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso à Eletricidade", subtitle = "Em percentual da população (2001 - 2017)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_acc_eletricitry.png")
 
 
 
evol_tam_pop <- media_bz_wd_sim_pop_2 %>%
   ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Tamanho da População", subtitle = "(2001 - 2017)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_tam_pop.png")
 
 
 
evol_acc_inter <- media_bz_wd_sim_inter_2 %>%
   ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso à Internet", subtitle = "Em percentual da população (2001 - 2017)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

 ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_acc_inter.png")
 
 
 
 
evol_acc_san <- media_bz_wd_sim_san_2 %>%
   ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso a Instalações Sanitárias Básicas", subtitle = "Em percentual da população (2001 - 2017)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_acc_san.png")
 
 
 
 
evol_efe_gov <- media_bz_wd_sim_gov_2  %>%
   ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução da Efetividade do Governo", subtitle = "Percepção da população na escala de -2,5 a +2,5 (2002 - 2017)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
 #  theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

 ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_efe_gov.png")
 
 
 
 
evol_idh <- media_bz_wd_sim_hdi_2  %>%
   ggplot( aes(x=Ano, y=Index, group=`Country`, color=`Country`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Índice de Desenvolvimento Humano", subtitle = "(2001 - 2018)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_idh.png")
 
 
 
#evol_index_gini_2 <- media_bz_wd_sim_gini_2  %>%
 #  ggplot( aes(x=Ano, y=Index, group=`Country Name`, color=`Country Name`)) +
  #  geom_line(size=0.9) +
  #scale_fill_gradientn(colours=rainbow(11)) + 
  #ggtitle("Evolução do Índice de Gini", subtitle = "(2001 - 2017)")   +
  #theme_fivethirtyeight() + 
  #theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   #theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

 #ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_index_gini_2.png")
 
 



```








```{r}


# Gráficos da evolucao dos indicadores medidos em números-índice

 
evol_idh_indice <- ind_media_bz_wd_sim_hdi_2  %>%
   ggplot( aes(x=Ano, y=Index, group=`Country`, color=`Country`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Índice de Desenvolvimento Humano (Nº índice)", subtitle = "(2001 - 2018)")   +
  theme_fivethirtyeight() + 
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold'), plot.subtitle = element_text( hjust=0.5, vjust=0.5)) +
   #theme(axis.title.y = element_text(angle = 90, color="black", size=8), axis.text.y = element_text(size = 5)) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, color="black", size=9, face=1), legend.title = element_blank()) #+
  #facet_wrap(~`Country Name`)

ggsave(file="/Users/MAC/Documents/Ambiente R/Brazilian-Social-and-Economic-Advances-in-21st-Century/Outputs/Plots/evol_idh_indice.png")
  




  

EVOL_GINI %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Índice de Gini") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold')) +
          ylab("Índice de Gini") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_gini.png")

EVOL_GINI_INDICE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Índice de Gini (Nº índice)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("Índice de Gini") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1))

 ggsave("evol_gini_indice.png")
 

EVOL_GDP_PC %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do PIB per capita (PPP)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold')) +
          ylab("PIB per capita (PPP)") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_gd_pc.png")

EVOL_GDP_PC_INDICE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do PIB per capita (PPP) (Nº índice)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("PIB per capita (PPP)") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1))

 ggsave("evol_gd_pc_indice.png")
 
 

EVOL_ACC_ELE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso à Eletricidade") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold')) +
          ylab("% da População com Acesso à Eletricidade") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_acc_ele.png")
 

EVOL_ACC_ELE_INDICE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso à Eletricidade (Nº índice)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("% da População com Acesso à Eletricidade") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) 

 ggsave("evol_acc_ele_indice.png")


GOV_EFE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução da Efetividade do Governo") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold')) +
          ylab("Grau de Efetividade do Governo") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_gov_efe.png")
 

INTER_ACC %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso à Internet") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold')) +
          ylab("% da População com Acesso à Internet") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_inter_acc.png")

INTER_ACC_INDICE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso à Internet (Nº índice)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("% da População com Acesso à Internet") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1))

 ggsave("evol_inter_acc_indice.png")
 

BAS_SAN %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso a Saneamento Básico") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, face='bold')) +
          ylab("% da População com Acesso a Saneamento Básico") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_bas_san.png")
 

BAS_SAN_INDICE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução do Acesso a Saneamento Básico (Nº índice)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("% da População com Acesso a Saneamento Básico") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1))

 ggsave("evol_bas_san_indice.png")

TOTAL_POP %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução da Poulação") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("Tamanho da População") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1)) +
  facet_wrap(~`Country Name`)

 ggsave("evol_pop_.png")
 

TOTAL_POP_INDICE %>%
  ggplot( aes(x=Year, y=Index, group=`Country Name`, color=`Country Name`)) +
    geom_line(size=0.9) +
  scale_fill_gradientn(colours=rainbow(11)) + 
  ggtitle("Evolução da Poulação (Nº índice)") +
  theme_fivethirtyeight() +
  theme(plot.title=element_text( hjust=0.5, vjust=0.5, size = 12, face='bold')) +
          ylab("Tamanho da População") +
  theme(axis.text.x = element_text(angle = 0, color="black", size=8, 
    face=1))

 ggsave("evol_pop_indice.png")



```




